from __future__ import annotations

import re
from typing import Any

from .ha import EntitySnapshot
from .models import ActionSpec, ConditionSpec, RuleDraft, ValidationResult

LOW_RISK_SERVICES = {
    "persistent_notification.create",
    "notify.notify",
    "light.turn_on",
    "light.turn_off",
    "switch.turn_on",
    "switch.turn_off",
    "scene.turn_on",
    "script.turn_on",
}

HIGH_RISK_DOMAINS = {"lock", "cover", "alarm_control_panel", "vacuum"}


def validate_draft(draft: RuleDraft, snapshot: EntitySnapshot) -> ValidationResult:
    errors: list[str] = []
    warnings: list[str] = []
    if draft.intent != "create_rule":
        errors.append(f"unsupported intent: {draft.intent}")
    if draft.missing_slots:
        warnings.extend(f"missing slot: {slot}" for slot in draft.missing_slots)
    if draft.trigger.kind == "state":
        if not snapshot.exists(draft.trigger.entity_id):
            errors.append(f"unknown trigger entity: {draft.trigger.entity_id}")
    elif draft.trigger.kind != "manual":
        errors.append(f"unsupported trigger kind: {draft.trigger.kind}")

    for condition in draft.conditions:
        if condition.kind == "state" and not snapshot.exists(condition.entity_id):
            errors.append(f"unknown condition entity: {condition.entity_id}")

    for action in draft.actions:
        if action.service not in LOW_RISK_SERVICES:
            errors.append(f"service is not allowlisted: {action.service}")
        target_entity = (action.target or {}).get("entity_id")
        if target_entity:
            domain = str(target_entity).split(".", 1)[0]
            if domain in HIGH_RISK_DOMAINS:
                errors.append(f"high-risk target is draft-only: {target_entity}")
            elif not snapshot.exists(target_entity):
                errors.append(f"unknown action target entity: {target_entity}")

    return ValidationResult.failure(errors, warnings) if errors else ValidationResult.success(warnings)


def _quote(value: Any) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _safe_id(draft: RuleDraft) -> str:
    base = re.sub(r"[^a-z0-9_]+", "_", draft.id.lower()).strip("_")
    return f"home_event_rule_bridge_{base}"


def _render_data(data: dict[str, Any], indent: int) -> list[str]:
    pad = " " * indent
    lines = []
    for key, value in data.items():
        lines.append(f"{pad}{key}: {_quote(value)}")
    return lines


def compile_automation_yaml(draft: RuleDraft) -> str:
    lines = [
        f"- id: {_quote(_safe_id(draft))}",
        f"  alias: {_quote('Bridge: ' + draft.explanation[:70])}",
        "  description: " + _quote("Generated by Home Event Rule Bridge after explicit approval."),
        "  trigger:",
    ]

    if draft.trigger.kind == "state":
        lines.extend(
            [
                "    - platform: state",
                f"      entity_id: {_quote(draft.trigger.entity_id)}",
            ]
        )
        if draft.trigger.to_state is not None:
            lines.append(f"      to: {_quote(draft.trigger.to_state)}")
    else:
        lines.extend(["    - platform: event", "      event_type: home_event_rule_bridge_manual"])

    if draft.conditions:
        lines.append("  condition:")
        for condition in draft.conditions:
            lines.extend(_render_condition(condition))
    else:
        lines.append("  condition: []")

    lines.append("  action:")
    for action in draft.actions:
        lines.extend(_render_action(action))
    lines.append("  mode: single")
    return "\n".join(lines) + "\n"


def compile_package_yaml(draft: RuleDraft) -> str:
    automation = compile_automation_yaml(draft)
    return "automation:\n" + "\n".join("  " + line if line else line for line in automation.splitlines()) + "\n"


def _render_condition(condition: ConditionSpec) -> list[str]:
    if condition.kind == "state":
        return [
            "    - condition: state",
            f"      entity_id: {_quote(condition.entity_id)}",
            f"      state: {_quote(condition.state)}",
        ]
    return ["    - condition: template", "      value_template: " + _quote("true")]


def _render_action(action: ActionSpec) -> list[str]:
    lines = [f"    - service: {action.service}"]
    if action.target:
        lines.append("      target:")
        for key, value in action.target.items():
            lines.append(f"        {key}: {_quote(value)}")
    if action.data:
        lines.append("      data:")
        lines.extend(_render_data(action.data, 8))
    return lines

